"""Initial versioned Python schema

Revision ID: 0001_python
Revises:
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_python"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("actor_id", sa.String(length=80), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=80), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_events_entity_id"), "audit_events", ["entity_id"], unique=False)
    op.create_table(
        "auth_throttles",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "configuration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("default_allowance", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("over_allowance", sa.String(length=10), nullable=False),
        sa.Column("max_away_percent", sa.Integer(), nullable=False),
        sa.CheckConstraint("over_allowance IN ('warn','block')"),
        sa.CheckConstraint("default_allowance >= 0"),
        sa.CheckConstraint("id = 1"),
        sa.CheckConstraint("max_away_percent BETWEEN 1 AND 100"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("minimum_present", sa.Integer(), nullable=False),
        sa.CheckConstraint("minimum_present >= 0"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mail_outbox",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("event_key", sa.String(length=200), nullable=False),
        sa.Column("recipient", sa.String(length=254), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("template", sa.String(length=40), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_error", sa.String(length=80), nullable=True),
        sa.Column("gmail_message_id", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('pending','sending','sent','failed','uncertain')"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_key"),
    )
    op.create_index(op.f("ix_mail_outbox_status"), "mail_outbox", ["status"], unique=False)
    op.create_table(
        "work_calendars",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calendar_holidays",
        sa.Column("calendar_id", sa.String(length=80), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["work_calendars.id"],
        ),
        sa.PrimaryKeyConstraint("calendar_id", "date"),
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("password_salt", sa.String(length=128), nullable=False),
        sa.Column("password_scheme", sa.String(length=30), nullable=False),
        sa.Column("department", sa.String(length=80), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("allowance_override", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("share_birthday", sa.Boolean(), nullable=False),
        sa.Column("calendar_id", sa.String(length=80), nullable=False),
        sa.Column("work_hours", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("employed_from", sa.Date(), nullable=True),
        sa.Column("employed_to", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('worker','manager','admin')"),
        sa.CheckConstraint("allowance_override IS NULL OR allowance_override >= 0"),
        sa.CheckConstraint(
            "employed_to IS NULL OR employed_from IS NULL OR employed_to >= employed_from"
        ),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["work_calendars.id"],
        ),
        sa.ForeignKeyConstraint(
            ["department"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(
        "ix_employees_department_active", "employees", ["department", "active"], unique=False
    )
    op.create_table(
        "annual_policies",
        sa.Column("user_id", sa.String(length=80), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("entitlement", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("adjustment", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("carryover", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("carryover_expiry", sa.Date(), nullable=True),
        sa.Column("prorate", sa.Boolean(), nullable=False),
        sa.CheckConstraint("entitlement >= 0 AND carryover >= 0"),
        sa.CheckConstraint("year BETWEEN 1900 AND 2200"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "year"),
    )
    op.create_table(
        "approval_delegations",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("manager_id", sa.String(length=80), nullable=False),
        sa.Column("delegate_id", sa.String(length=80), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        sa.CheckConstraint("manager_id <> delegate_id AND date_to >= date_from"),
        sa.ForeignKeyConstraint(
            ["delegate_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("manager_id", "delegate_id", "date_from", "date_to"),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=80), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_auth_sessions_expires_at"), "auth_sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "import_batches",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("user_id", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "fingerprint"),
    )
    op.create_table(
        "leave_requests",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("user_id", sa.String(length=80), nullable=False),
        sa.Column("user_name", sa.String(length=160), nullable=False),
        sa.Column("department", sa.String(length=80), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        sa.Column("half_start", sa.Boolean(), nullable=False),
        sa.Column("half_end", sa.Boolean(), nullable=False),
        sa.Column("days", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=160), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("source_key", sa.String(length=64), nullable=True),
        sa.Column("request_key", sa.String(length=80), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=True),
        sa.Column("over_allowance_acknowledged", sa.Boolean(), nullable=False),
        sa.CheckConstraint("status IN ('pending','approved','rejected','cancelled')"),
        sa.CheckConstraint("type IN ('vacaciones','ausencia','baja','permiso')"),
        sa.CheckConstraint("date_to >= date_from AND days > 0"),
        sa.ForeignKeyConstraint(
            ["department"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_key"),
        sa.UniqueConstraint("user_id", "request_key"),
    )
    op.create_index(
        "ix_requests_dept_status", "leave_requests", ["department", "status"], unique=False
    )
    op.create_index(
        "ix_requests_user_dates",
        "leave_requests",
        ["user_id", "date_from", "date_to"],
        unique=False,
    )
    op.create_table(
        "password_resets",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=80), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_password_resets_user_id"), "password_resets", ["user_id"], unique=False
    )
    op.create_table(
        "attachments",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("request_id", sa.String(length=80), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("mime_type", sa.String(length=80), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("uploaded_by", sa.String(length=160), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("size_bytes > 0"),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["leave_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attachments_request_id"), "attachments", ["request_id"], unique=False)
    op.create_table(
        "request_days",
        sa.Column("request_id", sa.String(length=80), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("units", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("hours", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.CheckConstraint("units > 0 AND hours > 0"),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["leave_requests.id"],
        ),
        sa.PrimaryKeyConstraint("request_id", "date"),
    )
    op.create_index("ix_request_days_date", "request_days", ["date"], unique=False)
    # Fixed reference data only. No default administrator, password or invented holidays.
    op.execute("INSERT INTO configuration VALUES (1, 22.5, 'warn', 30)")
    op.execute("INSERT INTO work_calendars VALUES ('default', 'Calendario general')")
    op.execute("""INSERT INTO departments (id, name, color, minimum_present) VALUES
        ('marketing', 'Marketing', '#e07a5f', 0),
        ('atencion_cliente', 'Atención al cliente', '#3d8bfd', 0),
        ('soporte_tecnico', 'Soporte técnico', '#8a9a1b', 0),
        ('logistica', 'Logística', '#9b5de5', 0)""")
    op.execute("""CREATE FUNCTION reject_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN RAISE EXCEPTION 'Audit events are append-only'; END; $$""")
    op.execute("""CREATE TRIGGER audit_no_update_delete BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION reject_audit_mutation()""")
    op.execute("""CREATE TRIGGER audit_no_truncate BEFORE TRUNCATE ON audit_events
        FOR EACH STATEMENT EXECUTE FUNCTION reject_audit_mutation()""")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_request_days_date", table_name="request_days")
    op.drop_table("request_days")
    op.drop_index(op.f("ix_attachments_request_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_index(op.f("ix_password_resets_user_id"), table_name="password_resets")
    op.drop_table("password_resets")
    op.drop_index("ix_requests_user_dates", table_name="leave_requests")
    op.drop_index("ix_requests_dept_status", table_name="leave_requests")
    op.drop_table("leave_requests")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_table("approval_delegations")
    op.drop_table("annual_policies")
    op.drop_index("ix_employees_department_active", table_name="employees")
    op.drop_table("employees")
    op.drop_table("calendar_holidays")
    op.drop_table("work_calendars")
    op.drop_index(op.f("ix_mail_outbox_status"), table_name="mail_outbox")
    op.drop_table("mail_outbox")
    op.drop_table("departments")
    op.drop_table("configuration")
    op.drop_table("auth_throttles")
    op.drop_index(op.f("ix_audit_events_entity_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
